package com.suikang.sales;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public final class ChannelXlsxExporter {
    private ChannelXlsxExporter() {}

    public static void export(List<Models.SalesOrder> orders,String channel,OutputStream target)throws Exception{
        ZipOutputStream z=new ZipOutputStream(new BufferedOutputStream(target));
        put(z,"[Content_Types].xml",contentTypes());put(z,"_rels/.rels",rootRels());put(z,"xl/workbook.xml",workbook());put(z,"xl/_rels/workbook.xml.rels",workbookRels());put(z,"xl/styles.xml",styles());put(z,"xl/worksheets/sheet1.xml",sheet(orders,channel));z.finish();z.flush();
    }
    private static String ch(String s){return s==null||s.trim().isEmpty()?"未设置":s.trim();}
    private static String esc(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    private static String c(String ref,String text,int style){return "<c r=\""+ref+"\" s=\""+style+"\" t=\"inlineStr\"><is><t xml:space=\"preserve\">"+esc(text)+"</t></is></c>";}
    private static String n(String ref,double v,int style){return "<c r=\""+ref+"\" s=\""+style+"\"><v>"+String.format(Locale.US,"%.4f",v)+"</v></c>";}
    private static String col(int x){StringBuilder s=new StringBuilder();while(x>0){x--;s.insert(0,(char)('A'+x%26));x/=26;}return s.toString();}
    private static String sheet(List<Models.SalesOrder> orders,String channel){
        StringBuilder x=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetViews><sheetView workbookViewId=\"0\"/></sheetViews><sheetFormatPr defaultRowHeight=\"18\"/><cols><col min=\"1\" max=\"1\" width=\"14\" customWidth=\"1\"/><col min=\"2\" max=\"2\" width=\"22\" customWidth=\"1\"/><col min=\"3\" max=\"6\" width=\"18\" customWidth=\"1\"/><col min=\"7\" max=\"13\" width=\"14\" customWidth=\"1\"/></cols><sheetData>");
        x.append("<row r=\"1\" ht=\"30\" customHeight=\"1\">").append(c("A1","惠州市岁康商贸 · 销售渠道订单汇总",1)).append("</row>");
        x.append("<row r=\"3\">").append(c("A3","销售渠道",5)).append(c("B3",channel==null?"全部渠道":channel,3)).append(c("D3","订单数",5)).append(n("E3",orders==null?0:orders.size(),3)).append("</row>");
        String[] h={"日期","订单编号","销售渠道","客户名称","产品名称","产品编号","数量","销售价","销售额","成本","毛利润","订单费用","订单净利润"};x.append("<row r=\"5\" ht=\"24\" customHeight=\"1\">");for(int i=0;i<h.length;i++)x.append(c(col(i+1)+"5",h[i],2));x.append("</row>");
        int r=6;double sales=0,cost=0,net=0;if(orders!=null)for(Models.SalesOrder o:orders){sales+=o.sales();cost+=o.goodsCost();net+=o.netProfit();boolean first=true;if(o.items.isEmpty()){x.append("<row r=\"").append(r).append("\">").append(c("A"+r,o.date,3)).append(c("B"+r,o.id,3)).append(c("C"+r,ch(o.salesChannel),3)).append(c("D"+r,o.customerName,3)).append(n("L"+r,o.freight+o.extraFees(),4)).append(n("M"+r,o.netProfit(),4)).append("</row>");r++;continue;}for(Models.OrderItem it:o.items){x.append("<row r=\"").append(r).append("\">").append(c("A"+r,o.date,3)).append(c("B"+r,o.id,3)).append(c("C"+r,ch(o.salesChannel),3)).append(c("D"+r,o.customerName,3)).append(c("E"+r,it.name,3)).append(c("F"+r,it.code,3)).append(n("G"+r,it.quantity,3)).append(n("H"+r,it.salePrice,4)).append(n("I"+r,it.revenue(),4)).append(n("J"+r,it.cost(),4)).append(n("K"+r,it.grossProfit(),4));if(first){x.append(n("L"+r,o.freight+o.extraFees(),4)).append(n("M"+r,o.netProfit(),4));first=false;}x.append("</row>");r++;}}
        int s=r+1;x.append("<row r=\"").append(s).append("\">").append(c("H"+s,"合计",5)).append(n("I"+s,sales,4)).append(n("J"+s,cost,4)).append(n("M"+s,net,4)).append("</row></sheetData><mergeCells count=\"1\"><mergeCell ref=\"A1:M1\"/></mergeCells><pageMargins left=\"0.3\" right=\"0.3\" top=\"0.5\" bottom=\"0.5\" header=\"0.2\" footer=\"0.2\"/></worksheet>");return x.toString();
    }
    private static void put(ZipOutputStream z,String p,String s)throws Exception{z.putNextEntry(new ZipEntry(p));z.write(s.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
    private static String contentTypes(){return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/></Types>";}
    private static String rootRels(){return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>";}
    private static String workbook(){return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"渠道订单汇总\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>";}
    private static String workbookRels(){return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>";}
    private static String styles(){return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><fonts count=\"3\"><font><sz val=\"11\"/><name val=\"Arial\"/></font><font><b/><sz val=\"16\"/><color rgb=\"FF183B56\"/><name val=\"Arial\"/></font><font><b/><sz val=\"11\"/><color rgb=\"FFFFFFFF\"/><name val=\"Arial\"/></font></fonts><fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF2267D2\"/></patternFill></fill></fills><borders count=\"2\"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style=\"thin\"/><right style=\"thin\"/><top style=\"thin\"/><bottom style=\"thin\"/><diagonal/></border></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"7\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"2\" fillId=\"2\" borderId=\"1\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"1\" xfId=\"0\"/><xf numFmtId=\"4\" fontId=\"0\" fillId=\"0\" borderId=\"1\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"1\" xfId=\"0\"/><xf numFmtId=\"10\" fontId=\"0\" fillId=\"0\" borderId=\"1\" xfId=\"0\"/></cellXfs></styleSheet>";}
}
